name: Monthly Python Script Execution

on:
  schedule:
    # Runs at 10:00 on the first day of every month
    - cron: '0 10 1 * *'
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt # Make sure to include a requirements.txt file if you have any dependencies

    - name: Run Python script
      env:
        ADS_API_TOKEN: ${{ secrets.ADS_API_TOKEN }}
      run: |
        year=$(date +'%Y')
        month=$(date +'%m')
        if [ "$month" -eq 1 ]; then
          PYTHON_SCRIPT_YEAR=$((year - 1))
          PYTHON_SCRIPT_MONTH=12
        else
          PYTHON_SCRIPT_YEAR=$year
          PYTHON_SCRIPT_MONTH=$((month - 1))
        fi
        python ads-papers-rsaa.py $PYTHON_SCRIPT_YEAR $PYTHON_SCRIPT_MONTH

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lunations/*.txt  # Add new month to lunations
        git commit -m "Automatic monthly update" -a || echo "No changes to commit"
        git push


